### ISSUE TITLE
Crash in Electron 28.0.0，Mac Pro 14 when run long time

### ISSUE THREAD

**Issue by luke358** [miniben-90/x-win#10]
When I run the software on Electron, there is a chance that it crashes.
this my code
```
import { WindowInfo, activeWindow } from '@miniben90/x-win';

type ActiveWindowInfo = {
  url?: string
  name: string
  title: string
  id: number
}

export async function getWindowInfo(): Promise<ActiveWindowInfo | undefined> {
  const windowInfo = await activeWindow()
  if (!windowInfo) {
    return undefined
  }
  return {
    name: (windowInfo as WindowInfo).info?.name,
    title: (windowInfo as WindowInfo).title,
    id: (windowInfo as WindowInfo).id
  }
}

setInterval(async () => {
      try {
        const activeWindowInfo = await getWindowInfo()
        if (activeWindowInfo?.name !== this.currentWindow?.name) {
          this.listener.forEach(func => func(activeWindowInfo))
          this.currentWindow = activeWindowInfo;
        }
      } catch (error) {
        console.error("获取窗口失败", error)
      }
    }, 1000)
```

**Comment by miniben-90** [comment]
Hi,
What operating system are you using?
Version of electron?
Did you try to run the recovery information throw a thread instead to call it directly?

Plus your code is not correct:
* all functions are synchronous so you don't have to use async and await

```typescript
setInterval(() => {
  try {
    const activeWindowInfo = getWindowInfo()
    if (activeWindowInfo?.name !== this.currentWindow?.name) {
      this.listener.forEach(func => func(activeWindowInfo))
      this.currentWindow = activeWindowInfo;
    }
  } catch (error) {
    console.error("获取窗口失败", error)
  }
}, 1000);
```

**Comment by luke358** [comment]
Model Name: MacBook Pro
      Model Identifier: Mac14,9
      Model Number: Z17G000B0CH/A
      Chip: Apple M2 Pro
      Total Number of Cores: 10 (6 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 8422.121.1
      OS Loader Version: 8422.121.1
      Serial Number (system): YVG09VG47X
      Hardware UUID: 55883C72-01CD-56C2-B856-B690E4D92817
      Provisioning UDID: 00006020-001A41120A98C01E
      Activation Lock Status: Disabled

**Comment by luke358** [comment]
I'm trying to create a minimal reproducible example, but so far, it's not quite working; it keeps crashing intermittently. I'm also attempting to collect crash reports, hoping they will be of help.

**Comment by luke358** [comment]
> Hi, What operating system are you using? Version of electron? Did you try to run the recovery information throw a worker instead to call it directly?
> 
> Plus your code is not correct:
> 
> * all functions are synchronous so you don't have to use async and await
> 
> ```ts
> setInterval(() => {
>   try {
>     const activeWindowInfo = getWindowInfo()
>     if (activeWindowInfo?.name !== this.currentWindow?.name) {
>       this.listener.forEach(func => func(activeWindowInfo))
>       this.currentWindow = activeWindowInfo;
>     }
>   } catch (error) {
>     console.error("获取窗口失败", error)
>   }
> }, 1000);
> ```

Yeah, you're right. I overlooked this aspect while attempting to reproduce the issue, but it does not affect the normal execution of the code.

**Comment by miniben-90** [comment]
> I'm trying to create a minimal reproducible example, but so far, it's not quite working; it keeps crashing intermittently. I'm also attempting to collect crash reports, hoping they will be of help.

Try to use `import { Worker } from 'node:worker_threads'` for calling activeWindow it will be more easy to catch an error if it come from it (https://nodejs.org/api/worker_threads.html)

**Comment by luke358** [comment]
This error occurred when I ran the code for an extended period of time.

[1229/102354.572106:WARNING:in_range_cast.h(38)] value -634136515 out of range
[1229/102354.585186:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)

**Comment by miniben-90** [comment]
I didn't see you are using `setInterval` be sure to write a clean code or you will have probably have memory leak.

example:

```typescript
let getActiveWindowInterval: NodeJS.Timeout | null;
function recoverActiveWindowInfo(): void {
  if (getActiveWindowInterval) {
    clearInterval(getActiveWindowInterval);
  }
  try {
    const activeWindowInfo = getWindowInfo();
    if (activeWindowInfo?.name !== this.currentWindow?.name) {
      this.listener.forEach(func => func(activeWindowInfo));
      this.currentWindow = activeWindowInfo;
    }
  } catch (error) {
    console.error("获取窗口失败", error);
  }
  getActiveWindowInterval = setInterval(() => recoverActiveWindowInfo(), 1000);
}

recoverActiveWindowInfo();
```

**Comment by luke358** [comment]
> I didn't see you are using `setInterval` be sure to write a clean code or you will have probably have memory leak.
> 
> example:
> 
> ```ts
> let getActiveWindowInterval: NodeJS.Timeout | null;
> function recoverActiveWindowInfo(): void {
>   if (getActiveWindowInterval) {
>     clearInterval(getActiveWindowInterval);
>   }
>   try {
>     const activeWindowInfo = getWindowInfo();
>     if (activeWindowInfo?.name !== this.currentWindow?.name) {
>       this.listener.forEach(func => func(activeWindowInfo));
>       this.currentWindow = activeWindowInfo;
>     }
>   } catch (error) {
>     console.error("获取窗口失败", error);
>   }
>   getActiveWindowInterval = setInterval(() => recoverActiveWindowInfo(), 1000);
> }
> 
> recoverActiveWindowInfo();
> ```

I have tried using console.log and noticed that in the Electron process, the `app.whenReady` only runs once. When I attempted to use @paymoapp/active-window as an alternative, I did not experience any crashes.

**Comment by miniben-90** [comment]
> I have tried using console.log and noticed that in the Electron process, the `app.whenReady` only runs once.

Did you try with my solution?
Did you also try using worker to optimize your code and avoid to stuck your main thread?

> When I attempted to use @paymoapp/active-window as an alternative, I did not experience any crashes.

Wee do not recover the data to the same way and in my case I also recover browsers URLs and other things. Are you using `getActiveWindow` or `subscribe`?

**Comment by miniben-90** [comment]
I make a new version with a listener function `subscribeActiveWindow` to remove your setInterval.
Don't forget to unsubscribe when your application close to kill properly the thread.

Example:

```typescript
// [...]
const activeWinSubId = subscribeActiveWindow(windowInfo => {
  if (windowInfo && (!this.currentWindow || windowInfo?.info?.name !== this.currentWindow?.name)) {
    const activeWindowInfo = { name: windowInfo.info.name, title: windowInfo.title, id: windowInfo.id };
    this.listener.forEach(func => func(activeWindowInfo));
    this.currentWindow = activeWindowInfo;
  }
});
// [...]

// Inside closing app

// [...]
unsubscribeActiveWindow(activeWinSubId);
// [...]
```

**Comment by luke358** [comment]
Yeah，thank you for do this，I will try it.
