### ISSUE TITLE
url retrieval problem in browser on electron

### ISSUE THREAD

**Issue by Brozzor** [miniben-90/x-win#16]
Hello, I've tried your module in a completely blank nodejs project and I manage to retrieve the urls from my chrome browser correctly, but when I do exactly the same thing in an electronjs project everything works except the url retrieval.

In nodeJS blank project :
![image](https://github.com/miniben-90/x-win/assets/46285168/5969b627-01c4-4e4c-ad20-15135a4e0256)

In electronJs Project (https://github.com/Deluze/electron-vue-template): 
![image](https://github.com/miniben-90/x-win/assets/46285168/28ddf2a5-c70d-4eaf-baf9-be84b65871a2)
![image](https://github.com/miniben-90/x-win/assets/46285168/d9387789-b452-47e9-937a-9c6406070229)

thank you for help

**Comment by miniben-90** [comment]
Hi,

For some reason with electron it is not possible to bring some data directly outside a worker when you use the sync functions (you will also have the issue with openWindows).

You have three solutions for the moment:

* Replace `activeWindow` with [`activeWindowAsync`](https://github.com/miniben-90/x-win/blob/cc0f257a21914db5f2c2b0fc988e124462aae68e/index.d.ts#L73) (it will create a thread to execute the code)
* Run your code inside a worker
* Using [`subscribeActiveWindow`](https://github.com/miniben-90/x-win/blob/cc0f257a21914db5f2c2b0fc988e124462aae68e/index.d.ts#L128)

You will have the same problem with Darwin (MacOS).

I hope that's help you!
