### ISSUE TITLE
Request for app icon

### ISSUE THREAD

**Issue by Srini-B** [miniben-90/x-win#28]
Hi, is it possible to get app icon on info obj along with existing, It would be helpful if we can get it by base64

**Comment by miniben-90** [comment]
Hi,
You can try new release `1.10.0`.
example:
```typescript
import { activeWindow, type WindowInfo, type IconInfo } from '@miniben90/x-win';

const window: WindowInfo = activeWindow();
const iconInfo: IconInfo = window.getIcon();
console.log(console);
```

**Comment by Srini-B** [comment]
Thanks, This works. Though 32x32 is small for my case, I get that storage also increases in proposition to dimensions.
