### ISSUE TITLE
Subscribe to ActiveWindow being moved

### ISSUE THREAD

**Issue by olsn** [miniben-90/x-win#32]
First of all: Thank you for the awesome tool!

My question is: Is it possible to somehow get a notification when a window is being moved or resized?

My current workaround is, to simply check every 500ms if the window has moved or resized by geting the active window every 500ms - it works okay, but it's not very pretty.

**Comment by miniben-90** [comment]
Hi, thanks

You can do something with a worker and/or events in Node.js by using a 500ms interval to observe any changes in window size or position.
