### ISSUE TITLE
get_open_windows not working on windows 32

### ISSUE THREAD

**Issue by mightymouse2045** [miniben-90/x-win#35]
I have just run a simple test with your example of get open windows. On my machine it works, but running it on windows 32 it's not working.

No error it is just empty. 

Any ideas - what can I do to debug this further?

**Comment by miniben-90** [comment]
Hi,
Can you be more specific:
* What's the system are you running it on?
* Which part are you using: Node.Js package or Rust package ?
* Can you provide me with a sample of your code?

**Comment by mightymouse2045** [comment]
Hi - it's in Rust. 
It's running on Windows Embedded 2010 SP1.
The code is literally just the example package.

cargo.toml:
`[package]
name = "test"
version = "1.0.0"
edition = "2018"

[dependencies]
x-win = "*"`

[main.rs using code from examples](https://github.com/miniben-90/x-win/blob/main/x-win-rs/examples/get_open_windows.rs)

**Comment by miniben-90** [comment]
Thanks for your information. As specified in the Readme file, this dependency works only with Windows 10 and Windows 11.
