### ISSUE TITLE
x-win.win32-x64-msvc.node not found

### ISSUE THREAD

**Issue by olan-go2** [miniben-90/x-win#36]
The module works on most of the windows PC, but some windows experiencing that this module doesn't exist.

Any idea why this dependency was not included in the package when bundled on an electron app?

**Comment by miniben-90** [comment]
Hi,
Can you be more specific:
* version(s) of Windows
* what are you using for building
* did you try to add the dependencies when you are building the app like this: `npm install --save-dev @miniben90/x-win-win32-x64-msvc @miniben90/x-win-win32-ia32-msvc --ignore-platform --ignore-engines` for Windows system
* Do you have some logs to help

**Comment by olan-go2** [comment]
- Versions of windows are: 10 and 11
- I am using a boilerplate to bootstrap the project: https://github.com/electron-react-boilerplate/electron-react-boilerplate
- I haven't tried this one, it's just weird because most of windows 10 works, and I only got a couple which doesn't.  _(I'll try this one)_
- The error is it could not found this `x-win.win32-x64-msvc.node`

**Comment by miniben-90** [comment]
If possible, try to unpack the asar file of your application (from a computer experiencing the 'not found' issue) to check whether the package @miniben90/x-win-win32-x64-msvc is present or not.

**Comment by olan-go2** [comment]
@miniben-90 The package `@miniben90/x-win-win32-x64-msvc` exists in the unpackaged asar file inside `node_modules`.

**Comment by miniben-90** [comment]
It's strange. If you have the files and the correct structure, it should work like any other Node dependency. I'll need the error stack or a reproducible project and environment to be able to help you.

**Comment by olan-go2** [comment]
Yeah, it's strange. Out of 300 Windows 10 units, 2 units are experiencing it.

Here's the error stack:
![error-main-process](https://github.com/user-attachments/assets/efb8bd8f-3dcf-4f00-820c-2c9d50e81893)

I suspect this is cause not properly resolving the path

**Comment by miniben-90** [comment]
I was able to reproduce your issue when I removed the `%localappdata%\Programs\electron-react-boilerplate\resources\app.asar.unpacked\node_modules\@miniben90\x-win-win32-x64-msvc\x-win.win32-x64-msvc.node` file on a virtual machine running Windows 10 with the latest updates. It seems something is interfering with it, or perhaps Windows Defender removed it for unknown reasons (or it wasn't correctly deployed during the installation of your Electron app).

**Comment by olan-go2** [comment]
The file exists in the app asar in node_modules, so the file wasn't removed. It's just strange that it wasn't imported it properly when accessing it. Any idea to solve this one?

**Comment by miniben-90** [comment]
I have no clue. If the file exists and it's in the right place it should work without any problems. The full path on the error stack is not visible but if it targeting the folder `..resources\app.asar.unpacked\node_modules..` it should work fine.
Without a reproducible environment I'm not able to help you.

**Comment by miniben-90** [comment]
No, it's not possible to wrap it in a function, the javascript part is generated by napi-rs. Also, it would be a breaking change.

* You can add your modifications to index.js with patch-package to do it easily.
* You can also run your recovery code in a worker.

And I don't think that overriding the path of the module will solve your problem.

**Comment by olan-go2** [comment]
The javascript part that needs to wrap in a function is the index.js, which is what I'm talking about. Yes, a it's a breaking change, but the only change we will make make is that only needs to call the function outside of the library.

Can you check this PR please, and let me know what you think? https://github.com/miniben-90/x-win/pull/37
