### ISSUE TITLE
Cannot find module '@miniben90/x-win-darwin-x64'

### ISSUE THREAD

**Issue by MohammedTaha** [miniben-90/x-win#39]
Hi, I tried to use `@miniben90/x-win` with electron.

While it works fine during development, when I package my app and tried to launch it, it fails with the following error

```
Uncaught Exception:
Error: Cannot find module '@miniben90/x-win-darwin-x64'
Require stack:
- /Applications/test-app.app/Contents/Resources/app.asar/node_modules/@miniben90/x-win/index.js
```
Looks like `@miniben90/x-win-darwin-x64` a private package, attempted to install it but then it requires github login. 
Is there anything I can do to avoid this issue?

**Comment by miniben-90** [comment]
Hi,
Thank you for your report. There is an issue with the auto-publishing workflow, and I'm looking into it.

**Comment by miniben-90** [comment]
You can try to update your project. I have published subpackages missing.
You should also ensure that the native Node package, such as @miniben90/x-win-darwin-x64, is unpacked if you're using the asar configuration with your Electron builder.

**Comment by miniben-90** [comment]
You need also to add optional packages when you run your building (https://github.com/miniben-90/x-win?tab=readme-ov-file#questions)[https://github.com/miniben-90/x-win?tab=readme-ov-file#questions]
