### ISSUE TITLE
Issue on win 11

### ISSUE THREAD

**Issue by Srini-B** [miniben-90/x-win#9]
Hi, getting the following issue on Windows 11, using on [electron-vite-react](https://github.com/electron-vite/electron-vite-react) template

`X [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/@paymoapp+real-idle@1.0.5/node_modules/@paymoapp/real-idle/build/Release/PaymoRealIdle.node

node_modules/.pnpm/@paymoapp+real-idle@1.0.5/node_modules/@paymoapp/real-idle/dist/index.js:9:20:
  9 │     addon = require('../build/Release/PaymoRealIdle.node'); // eslint-disable-line import/no-dynamic-require
    ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
X [ERROR] Could not resolve "mock-aws-s3"

node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
  43 │     const AWSMock = require('mock-aws-s3');
     ╵                             ~~~~~~~~~~~~~
You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
this error. You can also surround this "require" call with a try/catch block to handle this
failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "aws-sdk"

node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
  76 │   const AWS = require('aws-sdk');
     ╵                       ~~~~~~~~~
You can mark the path "aws-sdk" as external to exclude it from the bundle, which will remove this
error. You can also surround this "require" call with a try/catch block to handle this failure at
run-time instead of bundle-time.

X [ERROR] Could not resolve "nock"

node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
  112 │   const nock = require('nock');
      ╵                        ~~~~~~
You can mark the path "nock" as external to exclude it from the bundle, which will remove this
error. You can also surround this "require" call with a try/catch block to handle this failure at
run-time instead of bundle-time.

X [ERROR] No loader is configured for ".node" files: node_modules/.pnpm/@miniben90+x-win-win32-x64-msvc@1.3.1/node_modules/@miniben90/x-win-win32-x64-msvc/x-win.win32-x64-msvc.node

node_modules/.pnpm/@miniben90+x-win@1.3.1/node_modules/@miniben90/x-win/index.js:72:36:
  72 │             nativeBinding = require('@miniben90/x-win-win32-x64-msvc')
     ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:44:20 am [vite] error while updating dependencies:
Error: Build failed with 5 errors:
node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28: ERROR: Could not resolve "mock-aws-s3"
node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22: ERROR: Could not resolve "aws-sdk"
node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23: ERROR: Could not resolve "nock"
node_modules/.pnpm/@miniben90+x-win@1.3.1/node_modules/@miniben90/x-win/index.js:72:36: ERROR: No loader is configured for ".node" files: node_modules/.pnpm/@miniben90+x-win-win32-x64-msvc@1.3.1/node_modules/@miniben90/x-win-win32-x64-msvc/x-win.win32-x64-msvc.node
node_modules/.pnpm/@paymoapp+real-idle@1.0.5/node_modules/@paymoapp/real-idle/dist/index.js:9:20: ERROR: No loader is configured for ".node" files: node_modules/.pnpm/@paymoapp+real-idle@1.0.5/node_modules/@paymoapp/real-idle/build/Release/PaymoRealIdle.node
at failureErrorWithLog (D:\BeeBox\sandclock\sand\node_modules.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
at D:\BeeBox\sandclock\sand\node_modules.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
at D:\BeeBox\sandclock\sand\node_modules.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1525:9
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
main window closed
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by Srini-B** [comment]
I think part of it is caused by sqlite3

**Comment by Srini-B** [comment]
This is all due to direct invoke from React side without IPC call to SQLite, fixing that stopped the issue. 

I found I'm not getting URL on chrome, do I need to anything.

`currentWindow:  {
  id: 14976,
  os: 'win32',
  title: 'Issue on win 11 ┬╖ Issue #9 ┬╖ miniben-90/x-win - Google Chrome',
  position: { x: -8, y: -8, width: 1936, height: 1048 },
  info: {
    processId: 14976,
    path: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    name: 'Google Chrome',
    execName: 'chrome'
  },
  usage: { memory: 343064576 },
  url: ''
}`

**Comment by miniben-90** [comment]
Did you call `activeWindow` in a `worker` instated a direct call in your electron project?
What version of Chrome are you using?

**Comment by Srini-B** [comment]
![image](https://github.com/miniben-90/x-win/assets/22414119/7045a1bb-ece9-4e36-ac2d-e4a330bd4407)

chrome version - Version 120.0.6099.111 (Official Build) (64-bit)
windows - 23H2

**Comment by miniben-90** [comment]
Try to call it in a worker

**Comment by Srini-B** [comment]
Thanks, It works now
